#!/bin/bash
# Add the stack user we recommend folk use.

set -eu
set -o xtrace

useradd -m greghaynes -s /bin/zsh

cat > /etc/sudoers.d/greghaynes <<eof
# the stack user sometimes requires passwordless
# sudo for scripted operations.
greghanes ALL=(ALL) NOPASSWD:ALL
eof

chmod 0440 /etc/sudoers.d/greghaynes
visudo -c

if [ -e "/tmp/in_target.d/ssh-authorized-keys" ]; then
    mkdir -p /home/greghaynes/.ssh
    cat /tmp/in_target.d/ssh-authorized-keys >> /home/greghaynes/.ssh/authorized_keys
    chown -R greghaynes:greghaynes /home/greghaynes/.ssh
fi

ln -s DotFiles/.tmux.conf ~greghaynes/.tmux.conf
ln -s DotFiles/.zshrc ~greghaynes/.zshrc
chown -R greghaynes:greghaynes ~greghaynes
