#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

dest_dir=/usr/local/share/ca-certificates
mkdir -p $dest_dir

for ca in /tmp/dib-add-system-ca-certs/*; do
    cp $ca $dest_dir
done

update-ca-certificates
